apiVersion: v1
description: keycloak.
name: keycloak
version: 0.0.3
appVersion: 0.0.3
home: https://datalayer.io
icon: https://raw.githubusercontent.com/datalayer/datalayer/main/res/logo/datalayer-square.png
maintainers:
  - name: eric
    email: eric@datalayer.io
dependencies:
  - name: keycloak
    version: 10.1.0
    repository: https://codecentric.github.io/helm-charts
