apiVersion: v1
description: JupyterHub.
name: jupyterhub
version: 0.0.3
appVersion: 0.0.3
home: https://datalayer.io
sources:
- https://github.com/datalayer/datalayer/tree/main/etc/helm/jupyterub
icon: https://raw.githubusercontent.com/datalayer/datalayer/main/res/logo/datalayer-square.png
maintainers:
- name: eric
  email: eric@datalayer.io
dependencies:
  - name: jupyterhub
    version: 0.11.1
    repository: https://jupyterhub.github.io/helm-chart
