apiVersion: v1
description: keycloak.
name: keycloak
version: 0.0.3
appVersion: 0.0.3
home: https://datalayer.io
icon: https://docs.datalayer.io/logo/datalayer-square.png
maintainers:
- name: eric
  email: eric@datalayer.io
