#!/bin/bash

# THIS SCRIPT IS A WORKAROUND BECAUSE THE DEPENDENCIES ARE NOT AVAILABLE IN ANY CONDA CHANNEL


# TODO: MIGRATE ALL OF THEM TO CONDA PACKAGES AND PUSH THEM TO A CONDA CHANNEL
"${PREFIX}/bin/pip" install datalayer_core==1.0.23 jupyter_iam==1.2.6 jupyter_kernels==1.2.13
