apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-svc
  labels:
    app: {{ template "auth.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
#  type: ClusterIP
  ports:
  - port: {{ .Values.auth.port }}
    name: auth-http
  selector:
    app: {{ template "auth.name" . }}
    release: {{ .Release.Name }}
