apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  DSP_LDAP_BIND_PWD: {{ .Values.secret.DSP_LDAP_BIND_PWD | b64enc | quote }}
  DSP_JWT_SECRET: {{ .Values.secret.DSP_JWT_SECRET | b64enc | quote }}
stringData:
  t1: t1
