#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

if [ -z "$1" ]
then
  export FLAVOR=2.4
else
  export FLAVOR=$1
fi

echo -e $BOLD"Pushing Spark Docker Images for flavor '$FLAVOR'"$NOBOLD
echo

case "$FLAVOR" in

  2.4)
    cd $DLAOPT/spark && \
      ./bin/docker-image-tool.sh -r docker.io/datalayer -t 2.4.0 push && \
      docker push datalayer/spark-base:2.4.0
    ;;

  2.2)
    cd $DLAOPT/spark && \
      ./sbin/build-push-docker-images.sh -r docker.io/datalayer -t 2.2.0 push && \
      docker push datalayer/spark-base:2.2.0
    ;;

  *)
    echo "Unknown Flavor: $FLAVOR" 1>&2
    echo
    exit 1

esac
