#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Running Apache Spark K8S Integration Tests $BLUE[$@]"$NOCOLOR$NOBOLD
echo

# In order to prepare the environment for running the integration tests, the pre-integration-test step 
# must be run in Maven on the resource-managers/kubernetes/integration-tests module.

#  -Psparkr \
#  -Phive \
#  -Phive-thriftserver \
#  -Pnetlib-lgpl \
#  -Pyarn \
#  -Dyarn.version=$HADOOP_VERSION \
#  -Dspark.shade.packageName=org.eclipse \
#  -pl resource-managers/kubernetes/integration-tests \

# mvn \
#   -Pkubernetes \
#   -Pbigtop-dist \
#   -Pkubernetes-integration-tests \
#   -Phadoop-2.7 \
#   -Dhadoop.version=$HADOOP_VERSION \
#   -Dmaven.javadoc.skip=true \
#   -Dcheckstyle.skip=true \
#   -Dscalastyle.skip=true \
#   -Drat.skip=true \
#   -Dcobertura.skip=true \
#   -DskipTests \
#   pre-integration-test \
#   "$@"

# build/mvn -Pkubernetes \
#   -Pkubernetes-integration-tests  \
#   -pl resource-managers/kubernetes/integration-tests  \
#   -am \
#   -DskipTests \
# pre-integration-test

dla spark-mvn \
  pre-integration-test \
  -Pkubernetes-integration-tests \
  -DskipTests \
  "$@"
