#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

if [ -z "$1" ]
then
  export FLAVOR=2.4
else
  export FLAVOR=$1
fi

echo -e $BOLD"Pushing Spark Docker Images for flavor '$FLAVOR'"$NOBOLD
echo

case "$FLAVOR" in

  2.4)
    docker tag datalayer/spark-base:2.4.0 localhost:5000/spark-base:2.4.0
    docker push localhost:5000/spark-base:2.4.0
    docker tag datalayer/spark:2.4.0 localhost:5000/spark:2.4.0
    docker push localhost:5000/spark:2.4.0
    docker tag datalayer/spark-py:2.4.0 localhost:5000/spark-py:2.4.0
    docker push localhost:5000/spark-py:2.4.0
    docker tag datalayer/spark-r:2.4.0 localhost:5000/spark-r:2.4.0
    docker push localhost:5000/spark-r:2.4.0
    ;;

  2.2)
    docker tag datalayer/spark-base:2.2.0 localhost:5000/spark-base:2.2.0
    docker push localhost:5000/spark-base:2.2.0
    docker tag datalayer/spark-resource-staging-server:2.2.0 localhost:5000/spark-resource-staging-server:2.2.0
    docker push localhost:5000/spark-resource-staging-server:2.2.0
    docker tag datalayer/spark-shuffle-service:2.2.0 localhost:5000/spark-shuffle-service:2.2.0
    docker push localhost:5000/spark-shuffle-service:2.2.0
    docker tag datalayer/spark-init:2.2.0 localhost:5000/spark-init:2.2.0
    docker push localhost:5000:5000/spark-init:2.2.0
    docker tag datalayer/spark-driver:2.2.0 localhost:5000/spark-driver:2.2.0
    docker push localhost:5000/spark-driver:2.2.0
    docker tag datalayer/spark-driver-py:2.2.0 localhost:5000/spark-driver-py:2.2.0
    docker push localhost:5000/spark-driver-py:2.2.0
    docker tag datalayer/spark-executor:2.2.0 localhost:5000/spark-executor:2.2.0
    docker push localhost:5000/spark-executor:2.2.0
    docker tag datalayer/spark-executor-py:2.2.0 localhost:5000/spark-executor-py:2.2.0
    docker push localhost:5000/spark-executor-py:2.2.0
    ;;

  *)
    echo "Unknown Flavor: $FLAVOR" 1>&2
    echo
    exit 1

esac
