#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Serving Spark K8S Docs Site on http://localhost:4000"$NOBOLD$NOCOLOR
echo

cd $DLAHOME/repos/spark-docs

# xsbt previewSite
sbt previewSite
