ingress:
  enabled: true
  tls: []
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/auth/$2"
  rules:
    - 
      host: dsp-keycloak-http.dsp-keycloak.svc.cluster.local
      paths:
        - /auth(/|$)(.*)
extraEnv: |
  - name: KEYCLOAK_USER
    value: "admin"
  - name: KEYCLOAK_PASSWORD
    value: "{{ .Values.keycloak.password }}"
pgchecker:
  # Resource requests and limits for the pgchecker container
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "20m"
      memory: "32Mi"
