import {
    img_bgPricing,
    img_bg,
    img_bg0,
    img_bg2,
    img_bg3,
    img_bg4,
    img_bg5,
    img_bg6,
    img_bg7,
    img_bg8,
    img_bg9,
    img_bg10,
    img_bg11,
    img_bg12,
    img_card1,
    img_card2,
    img_card3,
    img_city,
    img_clintmckoy,
    img_dg1,
    img_dg2,
    img_dg3,
    img_dg6,
    img_dg9,
    img_dg10,
    img_office1,
    img_office2,
    img_office3,
    img_office4,
    img_office5,
    img_hunter,
    img_nasa_1lfI7wkGWZ4,
    img_nasa_5e9CmF_Ge9Y,
    img_nasa_pd4lo70LdbI,
} from "dspWidgets/Widgets";

const available_backgrounds = [
    img_bgPricing,
    img_bg,
//    img_bg0,
    img_bg2,
    img_bg3,
    img_bg4,
    img_bg5,
    img_bg6,
    img_bg7,
    img_bg8,
    img_bg9,
    img_bg10,
    img_bg11,
    img_bg12,
    img_card1,
    img_card2,
    img_card3,
    img_city,
    img_clintmckoy,
    img_dg1,
    img_dg2,
    img_dg3,
    img_dg6,
    img_dg9,
    img_dg10,
//    img_office1,
//    img_office2,
//    img_office3,
//    img_office4,
//    img_office5,
    img_hunter,
    img_nasa_1lfI7wkGWZ4,
    img_nasa_5e9CmF_Ge9Y,
    img_nasa_pd4lo70LdbI,
]

const selected_backgrounds = [
    img_clintmckoy,
    img_hunter,
    img_nasa_5e9CmF_Ge9Y,
    img_nasa_pd4lo70LdbI,
]

const active_backgrounds = selected_backgrounds;

const randomBackground = active_backgrounds[Math.floor(Math.random() * active_backgrounds.length)];

export { randomBackground as background };
