# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

FROM python:3.8.8

RUN mkdir /opt/datalayer

WORKDIR /opt/datalayer

RUN pip install kazoo

COPY utils /opt/datalayer/utils
RUN pip install -e ./utils

COPY auth /opt/datalayer/auth
RUN cd auth && pip install -e .

COPY library /opt/datalayer/library
RUN cd library && pip install -e .

WORKDIR /opt/datalayer/library

EXPOSE 9800

CMD ["python", "dsp_library/main.py"]
