package:
  name: datalayer
  version: "{{ DATALAYER_VERSION }}"

source:
  path: ../

channels:
  - datalayer

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
    - hatch-jupyter-builder>=0.5
    - hatchling
    - hatch-vcs
  run:
    - python
    - pip
#    - datalayer_core==1.0.23
#    - jupyter_iam==1.2.6
#    - jupyter_kernels==1.2.13

test:
  imports:
    - datalayer
