#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e """$GREEN
+ Simple, Collaborative, Extensible by Design.
+ Secured, Scalable, Multi Cloud by Default.
$NOCOLOR"""
echo -e $YELLOW"Version  $DLAVERSION"$NOCOLOR
echo -e $YELLOW"Home     $DLAHOME"$NOCOLOR

open https://github.com/datalayer/datalayer/blob/master/README.md
