#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Serving Datalayer Blog WEB Site on http://localhost:4001"$NOBOLD$NOCOLOR
echo

cd $DLAHOME/docs/blog && \
  rm -fr _site && \
  make serve
