#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Building Blueprint JS"$NOBOLD$NOCOLOR
echo

#  yarn compile && \
. $DLAHOME/opt/miniconda3/etc/profile.d/conda.sh && \
  cd $DLAHOME/repos/blueprint-js && \
  conda activate py2 && \
  yarn install && \
#  yarn verify && \
  yarn dist
