#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

CONDA_ENV=$1

echo -e $YELLOW$BOLD"Activating Conda Env [$GREEN$CONDA_ENV$YELLOW]"$NOBOLD$NOCOLOR
echo

. $DLAHOME/opt/miniconda3/etc/profile.d/conda.sh && \
  conda activate $CONDA_ENV && \
  export PATH=/opt/datalayer/opt/miniconda3/envs/$CONDA_ENV/bin:$PATH
