#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"Pushing Distribution Packages"$NOCOLOR$NOBOLD

# . $DLAOPT/miniconda3/etc/profile.d/conda.sh
# conda activate datalayer

source dists

for DIST in $DISTS; do

  REMOTE_FOLDER="$(cut -d'|' -f1 <<<"$DIST")"
  PACKAGE_FILE_NAME="$(cut -d'|' -f2 <<<"$DIST")"
  LOCAL_FOLDER="$(cut -d'|' -f3 <<<"$DIST")"

  REMOTE=s3://$REMOTE_FOLDER/$DLAVERSION/$PACKAGE_FILE_NAME
  LOCAL=$LOCAL_FOLDER/$PACKAGE_FILE_NAME

  echo
  echo -e $BOLD"Pushing "$LOCAL" to "$REMOTE$NOBOLD
  aws s3 cp $LOCAL $REMOTE
  echo

done
