#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"Pulling Distribution Packages"$NOCOLOR$NOBOLD
echo

source dists

for DIST in $DISTS; do

  REMOTE_FOLDER="$(cut -d'|' -f1 <<<"$DIST")"
  PACKAGE_FILE_NAME="$(cut -d'|' -f2 <<<"$DIST")"
  LOCAL_FOLDER="$(cut -d'|' -f3 <<<"$DIST")"

  REMOTE=s3://$REMOTE_FOLDER/$DLAVERSION/$PACKAGE_FILE_NAME
  LOCAL=$LOCAL_FOLDER/$PACKAGE_FILE_NAME

  FILE1="${LOCAL//.tgz/}"
  FILE="${FILE1//.tar.gz/}"
  echo "Removing $FILE"
  rm -fr $FILE
  echo

done
