#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

# REMOTE_FOLDER|PACKAGE_FILE_NAME|LOCAL_FOLDER

export DISTS="
datalayer-dist|kuber|$DLABIN \
datalayer-dist|hadoop-2.9.2.tar.gz|$DLAOPT \
datalayer-dist|hadoop-3.1.0.tar.gz|$DLAOPT \
datalayer-dist|hbase-2.0.0-bin.tar.gz|$DLAOPT \
datalayer-dist|solr-7.6.0.tgz|$DLAOPT \
datalayer-dist|spark-2.2.0-k8s-0.5.0-bin-hadoop-3.1.0.tgz|$DLAOPT \
datalayer-dist|zookeeper-3.4.12.tar.gz|$DLAOPT \
";
