#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

for f in $DLAHOME/src/svc/*/ $DLAHOME/docs/*/
do
  cd $f && \
    make clean
done

cd $DLAHOME
