#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Datalayer Help on Docker Swarm"$NOCOLOR$NOBOLD
echo

echo -e $YELLOW"""docker stack ps datalayer

docker service ls
docker service ps datalayer_jupyterhub --no-trunc
dla dsp-swarm-logs datalayer_jupyterhub

docker service scale datalayer_zoo=3
docker service ps datalayer_zoo

# traefik
open http://localhost:8089/dashboard/

# whoami
open http://localhost:8076/whoami
open https://${DLAHOST}/whoami
curl -k -H Host:${DLAHOST} https://localhost/whoami
dla dsp-swarm-up --scale whoami=2
for i in {0..20}; do curl -k -H Host:${DLAHOST} https://localhost/whoami; sleep 1s; done

# apis
open http://localhost:8989/api/doc
open https://${DLAHOST}/api/doc

# viz
open http://localhost:5000
open https://viz.${DLAHOST}

# ldap
open http://localhost:8083
open https://ldap.${DLAHOST}

# explorer
open http://localhost:9600
open https://${DLAHOST}
"""$NOCOLOR
