#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Pushing Datalayer DSP Docker Images"$NOCOLOR$NOBOLD
echo

source dsp-docker-images

for DOCKERIMAGE in "${DSP_DOCKER_IMAGES[@]}"
do
  echo
  echo -e $BOLD"Pushing $DOCKERIMAGE..."$NOBOLD
  docker push $DOCKERIMAGE
  if [ $? -eq 0 ]
  then
    echo
    echo -e $BOLD$GREEN"Push of docker image [${DOCKERFILE%/}] is successful."$NOCOLOR$NOBOLD
  else
    echo
    echo -e $BOLD$RED"Push of docker image [${DOCKERFILE%/}] failed..."$NOCOLOR$NOBOLD
    echo
    exit
  fi
  echo
done
