#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"Datalayer DSP Status"$NOCOLOR$NOBOLD
echo

DSP_SKIP_HEADER=true dla dsp-ls "$@"
