#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Building Datalayer DSP Docker Images"$NOCOLOR$NOBOLD
echo

declare -a FILES=(
  "apis"
  "iam"
  "library"
  "kuber"
  "studio"
  "keycloak"
  "solr"
  "whoami"
  "jupyterlab"
  "jupyterhub"
  "k8s-sidecar"
  )

more() {
  # HDFS.
  cd $DLAHOME/etc/docker/hdfs/base && \
    make build && \
    cd $DLAHOME/etc/docker/hdfs/dn && \
    make build && \
    cd $DLAHOME/etc/docker/hdfs/nn && \
    make build
  # Spark.
  cd $DLAHOME/etc/docker/spark && \
    make build
  # Jupyter.
  cd $DLAHOME/repos/jupyterhub-proxy-http && \
    git checkout datalayer && \
    docker build -t datalayer/jupyterhub-http-proxy:0.0.1 .
}

for FILE in "${FILES[@]}"
do
  echo -e $WHITE_BCK"Building Docker Image [$FILE]"$NOCOLOR
  echo
  cd $DLAHOME/etc/docker/$FILE && \
    make build
  if [ $? -eq 0 ]
  then
    echo
    echo -e $BOLD$GREEN"Docker Image [${FILE}] Build is Successful."$NOCOLOR$NOBOLD
  else
    echo
    echo -e $BOLD$RED"Docker Image [${FILE}] Build Failed..."$NOCOLOR$NOBOLD
    echo
    exit
  fi
  echo
done
