#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Serving Fabric UI Experiment on http://localhost:4322"$NOBOLD$NOCOLOR
echo

cd $DLAHOME/repos/fabric-ui && \
  yarn start-exp
