#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Serving Fabric UI Site on http://localhost:4321"$NOBOLD$NOCOLOR
echo

# yarn start --port 4323
cd $DLAHOME/repos/fabric-ui && \
  yarn start
