#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

if [ -z "$1" ]
then
  TOP_N=10
else
  TOP_N=$1
fi

echo -e $BOLD$YELLOW"Git Top $TOP_N files in size"$NOCOLOR$NOBOLD
echo

git ls-tree -r -t -l --full-name HEAD | sort -n -k 4 | tail -n $TOP_N
