#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting Apache HDFS Report"$NOCOLOR$NOBOLD

export DLA_HADOOP=yarn
export DLA_HADOOP_STATUS=starting

$HADOOP_HOME/bin/hdfs dfsadmin --config $HADOOP_CONF_DIR -report "$@"
