#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

DLA_SKIP_HEADER=true dla hdfs-stop
DLA_SKIP_HEADER=true dla hdfs-init
DLA_SKIP_HEADER=true dla hdfs-start
