#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting Apache HDFS..."$NOCOLOR$NOBOLD
echo

export DLA_HADOOP_STATUS=starting

# To debug Kerberos, use -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true -Djavax.net.debug=all

# Start the HDFS with the following command, run on the designated NameNode:
$HADOOP_HOME/bin/hdfs --daemon start namenode
# $HADOOP_HOME/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR start namenode

# Start the secondary namenode:
$HADOOP_HOME/bin/hdfs --daemon start secondarynamenode
# $HADOOP_HOME/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR start secondarynamenode

# Run a script to start DataNodes on all slaves:
$HADOOP_HOME/bin/hdfs --daemon start datanode
# $HADOOP_HOME/sbin/hadoop-daemon.sh --config $HADOOP_CONF_DIR start datanode

DLA_SKIP_HEADER=true dla hdfs-help
