#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting Apache HDFS Admin Report..."$NOCOLOR$NOBOLD
echo

export DATALAYER_HADOOP=yarn
export DATALAYER_HADOOP_STATUS=starting

$HADOOP_HOME/bin/hdfs dfsadmin -report "$@"
