#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

cd $DLAHOME/var/databooks

for i in *
do
  echo Creating HDFS Home Folder /user/$i
  sudo -u hdfs hdfs dfs -mkdir /user/$i
  sudo -u hdfs hdfs dfs -chown -R $i:hdfs /user/$i
  sudo -u hdfs hdfs dfs -chmod -R 700 /user/$i
done
