#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

if [ "$DLA_SHOW_HEADER" == "false" ]
then
  exit 0
fi

if [ "$DLA_SKIP_HEADER" == "true" ]
then
  exit 0
fi

echo -e $GREEN$BOLD"""            ___       __       __
  ───────  / _ \___ _/ /____ _/ /__ ___ _____ ____
 ───────  / // / _ \`/ __/ _ \`/ / _ \`/ // / -_) __/
───────  /____/\_,_/\__/\_,_/_/\_,_/\_, /\__/_/
                                  /___/

Datalayer Science Platform $DLAVERSION (c) 2019 https://datalayer.io"""
echo -e $NOBOLD$NOCOLOR
