#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Serving Helm Repository..."$NOCOLOR$NOBOLD
echo

cd $DLAHOME/etc/helm

for chart in */ ; do
  helm package "$chart" .
done

nohup helm serve \
  --address 0.0.0.0:80 \
  --repo-path . &
