#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"Helm Help"$NOCOLOR$NOBOLD

echo -e """
helm version
helm ls
helm dependency update
"""
