#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Starting Jupyterlab"$NOBOLD$NOCOLOR
echo

cd $DLAHOME/repos/jupyterlab && \
  jupyter lab --dev-mode --watch --browser chromium-browser
