#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"JupyterLab Start"$NOCOLOR$NOBOLD
echo

#  --ServerApp.token= \
jupyter lab \
  --notebook-dir=~/notebooks
