#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $YELLOW$BOLD"Building Jupyterlab"$NOBOLD$NOCOLOR
echo

cd $DLAHOME/repos/jupyterlab && \
  pip install -e . && \
  yarn clean && \
  yarn install && \
  yarn build && \
  jupyter lab build && \
  yarn build:test && \
  yarn test
