#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"JupyterLab Start DEV"$NOCOLOR$NOBOLD
echo

#  --ServerApp.login_handler_class=jupyter_auth.github.LoginHandler \
jupyter lab \
  --dev-mode \
  --ip 0.0.0.0 \
  --port 8888 \
  --watch \
  --ServerApp.token= \
  --notebook-dir=~/notebooks \
  --ServerApp.jpserver_extensions="{'jupyterlab': True, 'jupyter_auth': True}" \
  --no-browser \
  --extensions-in-dev-mode
