#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"JupyterLab Start"$NOCOLOR$NOBOLD
echo

#  --ServerApp.token= \
jupyter lab \
  --ip 0.0.0.0 \
  --port 8888 \
  --ServerApp.token= \
  --notebook-dir=~/notebooks \
  --ServerApp.jpserver_extensions="{'jupyterlab': True, 'jupyter_auth': True}" \
  --ServerApp.allow_origin='*' \
  --ServerApp.disable_check_xsrf=True ) \
  --no-browser
