#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Kubernetes Status"$NOCOLOR$NOBOLD
echo

# kubectl commands are now able to interact with minikube cluster.
echo -e $WHITE_BCK"NODES"$NOCOLOR
echo
kubectl get nodes --all-namespaces
echo
echo -e $WHITE_BCK"PODS"$NOCOLOR
echo
kubectl get pods --all-namespaces
echo
echo -e $WHITE_BCK"SERVICES"$NOCOLOR
echo
kubectl get svc --all-namespaces
echo
