#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Checking with Kubectl"$NOCOLOR$NOBOLD
echo

# This for loop waits until kubectl can access the api server that minikube has created.
for i in {1..150} # timeout for 5 minutes.
do
   kubectl get pods &> /dev/null
   if [ $? -ne 1 ]; then
      break
  fi
  echo 'Error while getting the pods - Sleeping for 2 seconds...'
  sleep 2
done
echo -e $GREEN"kubectl get nodes"$NOCOLOR
echo
kubectl get nodes
echo
echo -e $GREEN"kubectl get pods --all-namespaces"$NOCOLOR
echo
kubectl get pods --all-namespaces
echo
echo -e $GREEN"kubectl get services --all-namespaces"$NOCOLOR
echo
kubectl get services --all-namespaces
echo
