#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting LDAP"$NOCOLOR$NOBOLD
echo

$ADS_HOME/bin/apacheds.sh start

dla ldap-help

echo
