#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Stopping Minikube on Local Node"$NOCOLOR$NOBOLD
echo

DLA_SKIP_HEADER=true dla minikube-help "$@"

sudo systemctl stop localkube
sudo systemctl disable localkube
sudo systemctl stop kubelet
sudo systemctl disable kubelet
