#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Minikube Docker Env"$NOCOLOR$NOBOLD
echo

echo -e """Type the following in your shell to evaluate minikube docker-env.
$YELLOW
eval \$(minikube docker-env)
$NOCOLOR
eval $(minikube docker-env)
"""
