#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Installing Minikube"$NOCOLOR$NOBOLD
echo

export MINIKUBE_VERSION=1.2.0

install_on_linux() {

    echo 'For Linux, install kvm2 driver.'
    echo
    echo Ensure you have libvirt and qemu-kvm on your system...
    echo Debian/Ubuntu: sudo apt install libvirt-clients libvirt-daemon-system qemu-kvm
    echo Fedora/CentOS/RHEL: sudo yum install libvirt-daemon-kvm qemu-kvm
    echo

    echo "Add yourself to the libvirt group so you don't need to sudo"
    # NOTE: For older Debian/Ubuntu versions change the group to `libvirtd`
    sudo usermod -a -G libvirt $(whoami)
    echo Update your current session for the group change to take effect
    echo NOTE: For older Debian/Ubuntu versions change the group to libvirtd
    echo sudo newgrp libvirt && exit
    echo sudo chown -R $USER:libvirt /var/run/libvirt
    echo

    echo -e "Installing docker-machine-driver-kvm2"
    echo
    curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 \
      && sudo install docker-machine-driver-kvm2 /usr/local/bin \
      && rm docker-machine-driver-kvm2
    echo

    echo -e "Installing minikube ${MINIKUBE_VERSION} into /usr/local/bin"
    echo
    curl -Lo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/v${MINIKUBE_VERSION}/minikube-linux-amd64 \
        && chmod +x /usr/local/bin/minikube
    echo

}

install_on_macos() {

    echo 'Removing dhcpd_leases'
    echo
    sudo rm /var/db/dhcpd_leases
    echo

    echo "For MacOs, install hyperkit driver."
    echo
    curl -Lo docker-machine-driver-hyperkit https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
        && chmod +x docker-machine-driver-hyperkit \
        && sudo cp docker-machine-driver-hyperkit /usr/local/bin/ \
        && rm docker-machine-driver-hyperkit \
        && sudo chown root:wheel /usr/local/bin/docker-machine-driver-hyperkit \
        && sudo chmod u+s /usr/local/bin/docker-machine-driver-hyperkit
    echo

    echo -e "Installing minikube ${MINIKUBE_VERSION} into /usr/local/bin"
    echo
    curl -Lo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/v${MINIKUBE_VERSION}/minikube-darwin-amd64 \
        && chmod +x /usr/local/bin/minikube
    echo

}

DLA_SKIP_HEADER=true dla minikube-delete || true

case "${OS}" in
    LINUX)     install_on_linux;;
    MACOS)     install_on_macos;;
    *)         echo "Unsupported operating system ${OS}"
esac

DLA_SKIP_HEADER=true dla minikube-help "$@"
