#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Installing Apache Maven"$NOCOLOR$NOBOLD
echo

rm -fr $DLAOPT/apache-maven-$MAVEN_VERSION || true

cd $DLAOPT && \
  curl https://www-us.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar -xz
