#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Install Datalayer R Packages"$NOCOLOR$NOBOLD
echo

sudo R CMD BATCH $DLASBIN/R-packages-install.R /tmp/R-packages-install.R .out
cat /tmp/install_packages.R.out
