#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

for rep in $DLAHOME/repos/*/
do
#    dir=${dir%*/}
#    echo ${dir##*/}
  cd $rep
  git remote get-url --push origin
done | sort
