#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

source $DLASBIN/repos

echo -e $GREEN$BOLD"REPOSITORIES"
echo -e "____________"$NOBOLD

echo -e $NOCOLOR$GREEN$BOLD

for ((i=0; i<${#DSP_REPOS[@]}; i+=4)); do
  echo -e + ${DSP_REPOS[i]} ${DSP_REPOS[i+1]} ${DSP_REPOS[i+2]} ${DSP_REPOS[i+3]}
done

echo -e $NOCOLOR
