#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

source $DLASBIN/repos

echo -e $BOLD$YELLOW"Pulling from upstream and Pushing to origin"$NOCOLOR$NOBOLD
echo

for ((i=0; i<${#DSP_REPOS[@]}; i+=4)); do
  echo -e "$GREEN--- pulling and pushing $BOLD${DSP_REPOS[i]}$NOBOLD ---$NOCOLOR"
  cd $DLAHOME/repos/${DSP_REPOS[i]}
  echo -e $YELLOW
  echo -e "name:     ${DSP_REPOS[i]}"
  echo -e "folder:   ${PWD}"
  echo -e "origin:   ${DSP_REPOS[i+1]}"
  echo -e "upstream: ${DSP_REPOS[i+2]}"
  echo -e "branch:   ${DSP_REPOS[i+3]}"
  echo -e $NOCOLOR
  git checkout ${DSP_REPOS[i+3]}
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git checkout ${DSP_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  git pull origin ${DSP_REPOS[i+3]}
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git pull origin ${DSP_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  git fetch upstream
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git fetch upstream failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  git pull upstream ${DSP_REPOS[i+3]}
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git pull upstream ${DSP_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
#  git push origin ${DSP_REPOS[i+3]}
  git push origin ${DSP_REPOS[i+3]} --no-verify
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"push origin ${DSP_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  echo
done
