#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

source $DLASBIN/repos

echo -e $BOLD$YELLOW"Cloning the Datalayer Repositories..."$NOCOLOR$NOBOLD
echo

for ((i=0; i<${#DSP_REPOS[@]}; i+=4)); do
  echo -e $GREEN"--- cloning $BOLD${DSP_REPOS[i]}$NOBOLD ---"$NOCOLOR
  echo
  cd $DLAREPOS
  git clone --recursive  --recurse-submodules ${DSP_REPOS[i+1]} ${DSP_REPOS[i]} || true
  cd $DLAHOME/repos/${DSP_REPOS[i]}
  git remote rm origin || true
  git remote add origin ${DSP_REPOS[i+1]}
  git remote rm upstream || true
  git remote add upstream ${DSP_REPOS[i+2]}
  git push --set-upstream origin ${DSP_REPOS[i+3]}
  git fetch origin
  git remote -v
  echo
done
