#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

for rep in $DLAHOME/repos/*/
do
#    dir=${dir%*/}
#    echo ${dir##*/}
  cd $rep
  git remote get-url --push origin
done | sort
