#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

source $DLASBIN/repos

echo -e $BOLD$YELLOW"Status of the Datalayer Repositories..."$NOCOLOR$NOBOLD
echo

for ((i=0; i<${#DLA_REPOS[@]}; i+=4)); do
  echo -e $GREEN"--- git status $BOLD${DLA_REPOS[i]}$NOBOLD ---"$NOCOLOR
  echo
  cd $DLAHOME/repos/${DLA_REPOS[i]}
  git status
  echo
done
