#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

source $DLASBIN/repos

echo -e $GREEN$BOLD"REPOSITORIES"
echo -e "____________"$NOBOLD

echo -e $NOCOLOR$GREEN$BOLD

for ((i=0; i<${#DLA_REPOS[@]}; i+=4)); do
  echo -e + ${DLA_REPOS[i]} ${DLA_REPOS[i+1]} ${DLA_REPOS[i+2]} ${DLA_REPOS[i+3]}
done

echo -e $NOCOLOR
