#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

export DLA_REPOS_ORIGIN_REMOTE="
airflow|https://github.com/datalayer-contrib/airflow.git|https://github.com/apache/airflow.git|master \
ansible-spark-cluster|https://github.com/datalayer-contrib/ansible-spark-cluster.git|https://github.com/lresende/ansible-spark-cluster.git|master \
ansible-kubernetes-cluster|https://github.com/datalayer-contrib/ansible-kubernetes-cluster.git|https://github.com/lresende/ansible-kubernetes-cluster.git|master \
binderhub|https://github.com/datalayer-contrib/binderhub.git|https://github.com/jupyterhub/binderhub.git|master \
binderhub-deploy|https://github.com/datalayer-contrib/binderhub-deploy.git|https://github.com/jupyterhub/mybinder.org-deploy.git|master \
binderhub-docs|https://github.com/datalayer-contrib/binderhub-docs.git|https://github.com/jupyterhub/binder.git|master \
codesandbox|https://github.com/datalayer-contrib/codesandbox.git|https://github.com/codesandbox/codesandbox-client.git|master \
dex|https://github.com/datalayer-contrib/dex.git|https://github.com/dexidp/dex.git|master \
edu-data8-2017|https://github.com/datalayer-contrib/edu-data8-2017.git|https://github.com/data-8/materials-fa17.git|master \
edu-data8-datascience|https://github.com/datalayer-contrib/edu-data8-datascience.git|https://github.com/data-8/datascience.git|master \
edu-spacy|https://github.com/datalayer-contrib/edu-spacy.git|https://github.com/ines/spacy-course.git|master \
edu-starter-python|https://github.com/datalayer-contrib/edu-starter-python.git|https://github.com/ines/course-starter-python.git|master \
edu-starter-R|https://github.com/datalayer-contrib/edu-starter-R.git|https://github.com/ines/course-starter-r.git|master \
hadoop|https://github.com/datalayer-contrib/hadoop.git|https://github.com/apache/hadoop.git|trunk \
hbase|https://github.com/datalayer-contrib/hbase.git|https://github.com/apache/hbase.git|master \
hbase-indexer|https://github.com/datalayer-contrib/hbase-indexer.git|https://github.com/NGDATA/hbase-indexer.git|master \
hbase-phoenix|https://github.com/datalayer-contrib/hbase-phoenix.git|https://github.com/apache/phoenix.git|master \
ipfs|https://github.com/datalayer-contrib/ipfs.git|https://github.com/ipfs/go-ipfs.git|master \
ipywidgets|https://github.com/datalayer-contrib/ipywidgets|https://github.com/jupyter-widgets/ipywidgets.git|master \
ipywidgets-leaflet|https://github.com/datalayer-contrib/ipywidgets-leaflet.git|https://github.com/jupyter-widgets/ipyleaflet.git|master \
ipywidgets-tutorial|https://github.com/datalayer-contrib/ipywidgets-tutorial.git|https://github.com/jupyter-widgets/tutorial.git|master \
janusgraph|https://github.com/datalayer-contrib/janusgraph.git|https://github.com/JanusGraph/janusgraph.git|master \
jupyter|https://github.com/datalayer-contrib/jupyter.git|https://github.com/jupyter/jupyter.git|master \
jupyter-bqplot|https://github.com/datalayer-contrib/jupyter-bqplot.git|https://github.com/bloomberg/bqplot.git|master \
jupyter-cookiecutter|https://github.com/datalayer-contrib/jupyter-cookiecutter.git|https://github.com/jupyter-widgets/widget-ts-cookiecutter.git|master \
jupyter-core|https://github.com/datalayer-contrib/jupyter-core.git|https://github.com/jupyter/jupyter_core.git|master \
jupyter-dashboards|https://github.com/datalayer-contrib/jupyter-dashboards.git|https://github.com/jupyter/dashboards.git|master \
jupyter-design|https://github.com/datalayer-contrib/jupyter-design.git|https://github.com/jupyter/design.git|master \
jupyter-docker|https://github.com/datalayer-contrib/jupyter-docker.git|https://github.com/jupyter/docker-stacks.git|master \
jupyter-gateway-enterprise|https://github.com/datalayer-contrib/jupyter-gateway-enterprise.git|https://github.com/jupyter/enterprise_gateway.git|master \
jupyter-gateway-kernel|https://github.com/datalayer-contrib/jupyter-gateway-kernel.git|https://github.com/jupyter/kernel_gateway.git|master \
jupyter-kernel-all|https://github.com/datalayer-contrib/jupyter-kernel-all.git|https://github.com/minrk/allthekernels.git|master \
jupyter-kernel-client|https://github.com/datalayer-contrib/jupyter-kernel-client.git|https://github.com/jupyter/jupyter_client.git|master \
jupyter-kernel-magic-spark|https://github.com/datalayer-contrib/jupyter-kernel-magic-spark.git|https://github.com/jupyter-incubator/sparkmagic.git|master \
jupyter-kernel-magic-sql|https://github.com/datalayer-contrib/jupyter-kernel-magic-sql.git|https://github.com/pivotal-legacy/sql_magic.git|master \
jupyter-kernel-mgmt|https://github.com/datalayer-contrib/jupyter-kernel-mgmt.git|https://github.com/gateway-experiments/jupyter_kernel_mgmt.git|master \
jupyter-kernel-provider-kubernetes|https://github.com/datalayer-contrib/jupyter-kernel-provider-kubernetes.git|https://github.com/gateway-experiments/kubernetes_kernel_provider.git|master \
jupyter-kernel-provider-remote|https://github.com/datalayer-contrib/jupyter-kernel-provider-remote.git|https://github.com/gateway-experiments/remote_kernel_provider.git|master \
jupyter-kernel-python|https://github.com/datalayer-contrib/jupyter-kernel-python.git|https://github.com/ipython/ipykernel.git|master \
jupyter-kernel-spark-monitor|https://github.com/datalayer-contrib/jupyter-kernel-spark-monitor.git|https://github.com/krishnan-r/sparkmonitor.git|master \
jupyter-kernel-spark-moz|https://github.com/datalayer-contrib/jupyter-kernel-spark-moz.git|https://github.com/mozilla/jupyter-spark.git|master \
jupyter-kernel-spark-toree|https://github.com/datalayer-contrib/jupyter-kernel-spark-toree.git|https://github.com/apache/incubator-toree.git|master \
jupyter-nb2kg|https://github.com/datalayer-contrib/jupyter-nb2kg.git|https://github.com/jupyter/nb2kg.git|master \
jupyter-convert|https://github.com/datalayer-contrib/jupyter-convert.git|https://github.com/jupyter/nbconvert.git|master \
jupyter-dime|https://github.com/datalayer-contrib/jupyter-dime.git|https://github.com/jupyter/nbdime.git|master \
jupyter-format|https://github.com/datalayer-contrib/jupyter-format.git|https://github.com/jupyter/nbformat.git|master \
jupyter-grader|https://github.com/datalayer-contrib/jupyter-grader.git|https://github.com/jupyter/nbgrader.git|master \
jupyter-melt|https://github.com/datalayer-contrib/jupyter-melt.git|https://github.com/minrk/nbmelt.git|master \
jupyter-report|https://github.com/datalayer-contrib/jupyter-report.git|https://github.com/choldgraf/nbreport.git|master \
jupyter-notebook|https://github.com/datalayer-contrib/jupyter-notebook.git|https://github.com/jupyter/notebook.git|master \
jupyter-notebook-classic|https://github.com/datalayer-contrib/jupyter-notebook-classic.git|https://github.com/zsailer/nbclassic.git|master \
jupyter-packaging|https://github.com/datalayer-contrib/jupyter-packaging.git|https://github.com/jupyter/jupyter-packaging.git|master \
jupyter-pizzabutton|https://github.com/datalayer-contrib/jupyter-pizzabutton.git|https://github.com/peterskipper/pizzabutton.git|master \
jupyter-protocol|https://github.com/datalayer-contrib/jupyter-protocol.git|https://github.com/gateway-experiments/jupyter_protocol.git|master \
jupyter-proxy-R|https://github.com/datalayer-contrib/jupyter-proxy-R.git|https://github.com/jupyterhub/jupyter-rsession-proxy.git|master \
jupyter-proxy-server|https://github.com/datalayer-contrib/jupyter-proxy-server.git|https://github.com/jupyterhub/jupyter-server-proxy.git|master \
jupyter-pyzmq|https://github.com/datalayer-contrib/jupyter-pyzmq.git|https://github.com/zeromq/pyzmq.git|master \
jupyter-server|https://github.com/datalayer-contrib/jupyter-server.git|https://github.com/jupyter/jupyter_server.git|master \
jupyter-server-tests|https://github.com/datalayer-contrib/jupyter-server-tests.git|https://github.com/zsailer/jupyter_server_tests.git|master \
jupyter-traitlets|https://github.com/datalayer-contrib/jupyter-traitlets.git|https://github.com/ipython/traitlets.git|master \
jupyter-viewer|https://github.com/datalayer-contrib/jupyter-viewer.git|https://github.com/jupyter/nbviewer.git|master \
jupyterhub|https://github.com/datalayer-contrib/jupyterhub.git|https://github.com/jupyterhub/jupyterhub.git|master \
jupyterhub-auth-ldap|https://github.com/datalayer-contrib/jupyterhub-auth-ldap.git|https://github.com/jupyterhub/ldapauthenticator.git|master \
jupyterhub-auth-oauth|https://github.com/datalayer-contrib/jupyterhub-auth-oauth.git|https://github.com/jupyterhub/oauthenticator.git|master \
jupyterhub-auth-tmp|https://github.com/datalayer-contrib/jupyterhub-auth-tmp.git|https://github.com/jupyterhub/tmpauthenticator.git|master \
jupyterhub-docker|https://github.com/datalayer-contrib/jupyterhub-docker.git|https://github.com/jupyterhub/jupyterhub-deploy-docker.git|master \
jupyterhub-gitpuller|https://github.com/datalayer-contrib/jupyterhub-gitpuller.git|https://github.com/jupyterhub/nbgitpuller.git|master \
jupyterhub-grader|https://github.com/datalayer-contrib/jupyterhub-grader.git|https://github.com/jupyterhub/jupyterhub-deploy-teaching.git|master \
jupyterhub-helm|https://github.com/datalayer-contrib/jupyterhub-helm.git|https://github.com/jupyterhub/helm-chart.git|master \
jupyterhub-k8s|https://github.com/datalayer-contrib/jupyterhub-k8s.git|https://github.com/jupyterhub/zero-to-jupyterhub-k8s.git|master \
jupyterhub-kerberos|https://github.com/datalayer-contrib/jupyterhub-kerberos.git|https://github.com/jupyterhub/jupyterhub-example-kerberos.git|master \
jupyterhub-proxy-http|https://github.com/datalayer-contrib/jupyterhub-proxy-http.git|https://github.com/jupyterhub/configurable-http-proxy.git|master \
jupyterhub-spawner-batch|https://github.com/datalayer-contrib/jupyterhub-spawner-batch.git|https://github.com/jupyterhub/batchspawner.git|master \
jupyterhub-spawner-docker|https://github.com/datalayer-contrib/jupyterhub-spawner-docker.git|https://github.com/jupyterhub/dockerspawner.git|master \
jupyterhub-spawner-k8s|https://github.com/datalayer-contrib/jupyterhub-spawner-k8s.git|https://github.com/jupyterhub/kubespawner.git|master \
jupyterhub-spawner-sudo|https://github.com/datalayer-contrib/jupyterhub-spawner-sudo.git|https://github.com/jupyterhub/sudospawner.git|master \
jupyterhub-spawner-systemd|https://github.com/datalayer-contrib/jupyterhub-spawner-systemd.git|https://github.com/jupyterhub/systemdspawner.git|master \
jupyterhub-spawner-wrap|https://github.com/datalayer-contrib/jupyterhub-spawner-wrap.git|https://github.com/jupyterhub/wrapspawner.git|master \
jupyterhub-tutorial|https://github.com/datalayer-contrib/jupyterhub-tutorial.git|https://github.com/jupyterhub/jupyterhub-tutorial.git|master \
jupyterlab|https://github.com/datalayer-contrib/jupyterlab.git|https://github.com/jupyterlab/jupyterlab.git|master \
jupyterlab-commenting|https://github.com/datalayer-contrib/jupyterlab-commenting.git|https://github.com/jupyterlab/jupyterlab-commenting.git|master \
jupyterlab-cookiecutter-extension|https://github.com/datalayer-contrib/jupyterlab-cookiecutter-extension.git|https://github.com/jupyterlab/extension-cookiecutter-ts.git|master \
jupyterlab-cookiecutter-mimerender|https://github.com/datalayer-contrib/jupyterlab-cookiecutter-mimerender.git|https://github.com/jupyterlab/mimerender-cookiecutter-ts.git|master \
jupyterlab-data-explorer|https://github.com/datalayer-contrib/jupyterlab-data-explorer.git|https://github.com/jupyterlab/jupyterlab-data-explorer.git|master \
jupyterlab-demo|https://github.com/datalayer-contrib/jupyterlab-demo.git|https://github.com/jupyterlab/jupyterlab-demo.git|master \
jupyterlab-drawio|https://github.com/datalayer-contrib/jupyterlab-drawio.git|https://github.com/quantstack/jupyterlab-drawio.git|master \
jupyterlab-extension-examples|https://github.com/datalayer-contrib/jupyterlab-extension-examples.git|https://github.com/jtpio/jupyterlab-extension-tutorial|master \
jupyterlab-git|https://github.com/datalayer-contrib/jupyterlab-git.git|https://github.com/jupyterlab/jupyterlab-git.git|master \
jupyterlab-github|https://github.com/datalayer-contrib/jupyterlab-github.git|https://github.com/jupyterlab/jupyterlab-github.git|master \
jupyterlab-google-drive|https://github.com/datalayer-contrib/jupyterlab-google-drive.git|https://github.com/jupyterlab/jupyterlab-google-drive.git|master \
jupyterlab-hub|https://github.com/datalayer-contrib/jupyterlab-hub.git|https://github.com/jupyterhub/jupyterlab-hub.git|master \
jupyterlab-latex|https://github.com/datalayer-contrib/jupyterlab-latex.git|https://github.com/jupyterlab/jupyterlab-latex.git|master \
jupyterlab-lumino|https://github.com/datalayer-contrib/jupyterlab-lumino.git|https://github.com/jupyterlab/lumino.git|master \
jupyterlab-phoila|https://github.com/datalayer-contrib/jupyterlab-phoila.git|https://github.com/vidartf/phoila.git|master \
jupyterlab-pixiedust|https://github.com/datalayer-contrib/jupyterlab-pixiedust.git|https://github.com/pixiedust/pixiedust.git|master \
jupyterlab-renderers|https://github.com/datalayer-contrib/jupyterlab-renderers.git|https://github.com/jupyterlab/jupyter-renderers.git|master \
jupyterlab-server|https://github.com/datalayer-contrib/jupyterlab-server.git|https://github.com/jupyterlab/jupyterlab_server.git|master \
jupyterlab-thebe|https://github.com/datalayer-contrib/jupyterlab-thebe.git|https://github.com/minrk/thebelab.git|master \
jupyterlab-toastify|https://github.com/datalayer-contrib/jupyterlab-toastify.git|https://github.com/fcollonval/jupyterlab_toastify.git|master \
jupyterlab-toc|https://github.com/datalayer-contrib/jupyterlab-toc.git|https://github.com/jupyterlab/jupyterlab-toc.git|master \
jupyterlab-voyager|https://github.com/datalayer-contrib/jupyterlab-voyager.git|https://github.com/altair-viz/jupyterlab_voyager.git|master \
jupyterlab-xkcd|https://github.com/datalayer-contrib/jupyterlab-xkcd.git|https://github.com/jupyterlab/jupyterlab_xkcd.git|master \
k8s-airflow-operator|https://github.com/datalayer-contrib/k8s-airflow-operator.git|https://github.com/GoogleCloudPlatform/airflow-operator.git|master \
k8s-aws-authenticator|https://github.com/datalayer-contrib/k8s-aws-authenticator.git|https://github.com/kubernetes-sigs/aws-iam-authenticator.git|master \
k8s-aws-quickstart|https://github.com/datalayer-contrib/k8s-aws-quickstart.git|https://github.com/heptio/aws-quickstart.git|master \
k8s-cluster-api|https://github.com/datalayer-contrib/k8s-cluster-api.git|https://github.com/kubernetes-sigs/cluster-api.git|master \
k8s-cluster-api-aws|https://github.com/datalayer-contrib/k8s-cluster-api-aws.git|https://github.com/kubernetes-sigs/cluster-api-provider-aws.git|master \
k8s-cluster-api-azure|https://github.com/datalayer-contrib/k8s-cluster-api-azure.git|https://github.com/kubernetes-sigs/cluster-api-provider-azure.git|master \
k8s-cluster-api-gcp|https://github.com/datalayer-contrib/k8s-cluster-api-gcp.git|https://github.com/kubernetes-sigs/cluster-api-provider-gcp.git|master \
k8s-cluster-api-ssh|https://github.com/datalayer-contrib/k8s-cluster-api-ssh.git|https://github.com/samsung-cnct/cluster-api-provider-ssh.git|master \
k8s-dashboard|https://github.com/datalayer-contrib/k8s-dashboard.git|https://github.com/kubernetes/dashboard.git|master \
k8s-kubicorn|https://github.com/datalayer-contrib/k8s-kubicorn.git|https://github.com/kubicorn/kubicorn.git|master \
k8s-kubicorn-bootstrap|https://github.com/datalayer-contrib/k8s-kubicorn-bootstrap.git|https://github.com/kubicorn/bootstrap.git|master \
k8s-kubicorn-controller|https://github.com/datalayer-contrib/k8s-kubicorn-controller.git|https://github.com/kubicorn/controller.git|master \
k8s-spark-operator|https://github.com/datalayer-contrib/k8s-spark-operator.git|https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.git|master \
k8s-velero|https://github.com/datalayer-contrib/k8s-velero.git|https://github.com/heptio/velero.git|master \
k8s-velero-plugin|https://github.com/datalayer-contrib/k8s-velero-plugin.git|https://github.com/heptio/velero-plugin-example.git|master \
kubeflow|https://github.com/datalayer-contrib/kubeflow.git|https://github.com/kubeflow/kubeflow.git|master \
kubeflow-examples|https://github.com/datalayer-contrib/kubeflow-examples.git|https://github.com/kubeflow/examples.git|master \
kubeflow-kvc|https://github.com/datalayer-contrib/kubeflow-kvc.git|https://github.com/IntelAI/vck.git|master \
kubeflow-tf-operator|https://github.com/datalayer-contrib/kubeflow-tf-operator.git|https://github.com/kubeflow/tf-operator.git|master \
nteract|https://github.com/datalayer-contrib/nteract.git|https://github.com/nteract/nteract.git|master \
nteract-data-explorer|https://github.com/datalayer-contrib/nteract-data-explorer.git|https://github.com/benrussert/data-explorer.git|master \
nteract-hydrogen|https://github.com/datalayer-contrib/nteract-hydrogen.git|https://github.com/nteract/hydrogen.git|master \
nteract-ion|https://github.com/datalayer-contrib/nteract-ion.git|https://github.com/nteract/ion.git|master \
nteract-vdom|https://github.com/datalayer-contrib/nteract-vdom.git|https://github.com/nteract/vdom.git|master \
papermill|https://github.com/datalayer-contrib/papermill.git|https://github.com/nteract/papermill.git|master \
papermill-bookstore|https://github.com/datalayer-contrib/papermill-bookstore.git|https://github.com/nteract/bookstore.git|master \
papermill-paperboy|https://github.com/datalayer-contrib/papermill-paperboy.git|https://github.com/timkpaine/paperboy.git|master \
papermill-scrapbook|https://github.com/datalayer-contrib/papermill-scrapbook.git|https://github.com/nteract/scrapbook.git|master \
spark|https://github.com/datalayer-contrib/spark.git|https://github.com/apache/spark.git|master \
spark-hbase|https://github.com/datalayer-contrib/spark-hbase-connector.git|https://github.com/hortonworks-spark/shc.git|master \
spark-kafka|https://github.com/datalayer-contrib/spark-kafka-connector.git|https://github.com/hortonworks-spark/skc.git|master \
spark-solr|https://github.com/datalayer-contrib/spark-solr.git|https://github.com/lucidworks/spark-solr.git|master \
voila|https://github.com/datalayer-contrib/voila.git|https://github.com/voila-dashboards/voila.git|master \
voila-gridstack|https://github.com/datalayer-contrib/voila-gridstack.git|https://github.com/quantstack/voila-gridstack.git|master \
voila-vuetify|https://github.com/datalayer-contrib/voila-vuetify.git|https://github.com/quantstack/voila-vuetify.git|master \
vscode|https://github.com/datalayer-contrib/vscode.git|https://github.com/microsoft/vscode.git|master \
vscode-server|https://github.com/datalayer-contrib/vscode-server.git|https://github.com/cdr/code-server.git|master \
vscode-extension-samples|https://github.com/datalayer-contrib/vscode-extension-samples.git|https://github.com/microsoft/vscode-extension-samples.git|master \
vscode-python|https://github.com/datalayer-contrib/vscode-python.git|https://github.com/microsoft/vscode-python.git|master \
";

DLA_REPOS=()
for repo in $DLA_REPOS_ORIGIN_REMOTE; do
  name=$(cut -d'|' -f1 <<<$repo)
  origin=$(cut -d'|' -f2 <<<$repo)
  remote=$(cut -d'|' -f3 <<<$repo)
  branch=$(cut -d'|' -f4 <<<$repo)
  DLA_REPOS+=($name)
  DLA_REPOS+=($origin)
  DLA_REPOS+=($remote)
  DLA_REPOS+=($branch)
done
