#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"Installing Apache Solr"$NOCOLOR$NOBOLD
echo

rm -fr $DLAOPT/solr* || true

cd $DLAOPT && \
  curl https://downloads.apache.org/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz | tar -xz && \
  ln -s solr-${SOLR_VERSION} solr
