#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Stopping Apache Solr..."$NOBOLD$NOCOLOR
echo

$SOLR_HOME/bin/solr stop -all

echo
