#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Generating Apache Solr Configuration from Template"$NOCOLOR$NOBOLD
echo

echo $SOLR_CONF_DIR
ls -alp $SOLR_CONF_DIR
