#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $YELLOW$BOLD"Stopping Apache Solr..."$NOBOLD$NOCOLOR
echo

$SOLR_HOME/bin/solr stop -all

echo
