#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting Apache Spark Shell on YARN"$NOCOLOR$NOBOLD
echo

export SPARK_DIST_CLASSPATH=$(hadoop classpath)

$SPARK_HOME/bin/spark-shell \
  --conf spark.sql.catalogImplementation=in-memory \
  --conf spark.sql.warehouse.dir=/tmp/spark-warehouse \
  --driver-memory 3g \
  --executor-memory 3g \
  --master yarn \
  --deploy-mode client \
  "$@"
