#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

sed '/SHELL_EXCLUDE/d' "$@" | datalayer spark-shell --executor-memory 14G --driver-memory 4G
