#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Building Apache Spark with Maven ["$BLUE"$@"$YELLOW"]"$NOCOLOR$NOBOLD
echo

export HADOOP_VERSION=2.9.0

#  -Psparkr \
#  -Phive \
#  -Phive-thriftserver \
#  -Pnetlib-lgpl \
#  -pl resource-managers/kubernetes/core -am \
#  -Dmaven.install.skip=false \
#  -Dspark.shade.packageName=org.eclipse \
mvn \
  -Pkubernetes \
  -Pbigtop-dist \
  -Phadoop-2.7 \
  -Dhadoop.version=$HADOOP_VERSION \
  -Pyarn \
  -Dyarn.version=$HADOOP_VERSION \
  -Dmaven.javadoc.skip=true \
  -Dcheckstyle.skip=true \
  -Dscalastyle.skip=true \
  -Drat.skip=true \
  -Dcobertura.skip=true \
  -Dspotbugs.skip=true \
  "$@"
