#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting Apache Spark Shell..."$NOCOLOR$NOBOLD
echo

export DLA_HADOOP_STATUS=starting

scala_file=$1

shift 1

arguments=$@

# set +o posix  # to enable process substitution when not running on bash

# spark-shell --master yarn \
#             --deploy-mode client \
#             --queue default \
#             --driver-memory 2g \
#             --executor-memory 4g \
#             --num-executors 10 \
#             -i <(echo 'val args = "'$arguments'".split("\\s+")' ; cat $scala_file)

spark-shell -i <(echo 'val args = "'$arguments'".split("\\s+")'; cat $scala_file)
