#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $BOLD$YELLOW"Top Files"$NOCOLOR$NOBOLD
echo

find . -printf '%s %p\n' | sort -nr| head
