#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Stopping Apache YARN..."$NOCOLOR$NOBOLD
echo

export DLA_HADOOP=yarn
export DLA_HADOOP_STATUS=stopping

# Stop the WebAppProxy server. If multiple servers are used with load balancing it should be run on each of them:
# $HADOOP_HOME/bin/yarn --daemon stop proxyserver
# $HADOOP_HOME/sbin/yarn-daemon.sh stop proxyserver --config $HADOOP_CONF_DIR

# Stop the MapReduce JobHistory Server with the following command, run on the designated server:
$HADOOP_HOME/bin/yarn --daemon stop timelineserver
# $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh stop historyserver --config $HADOOP_CONF_DIR

# Run a script to stop NodeManagers on all slaves:
$HADOOP_HOME/bin/yarn --daemon stop nodemanager
# $HADOOP_HOME/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR stop nodemanager

# Stop the ResourceManager with the following command, run on the designated ResourceManager:
$HADOOP_HOME/bin/yarn --daemon stop resourcemanager
# $HADOOP_HOME/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR stop resourcemanager

