#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

sed -e "s|DLA_HADOOP_DATA_DIR|$DLA_HADOOP_DATA_DIR|g" $DLA_HADOOP_CONF_TEMPLATE_DIR/core-site.template.xml > $DLAHOME/etc/conf/hadoop/core-site.xml
sed -e "s|DLA_HADOOP_DATA_DIR|$DLA_HADOOP_DATA_DIR|g" $DLA_HADOOP_CONF_TEMPLATE_DIR/mapred-site.template.xml > $DLAHOME/etc/conf/hadoop/mapred-site.xml
sed -e "s|DLA_HADOOP_DATA_DIR|$DLA_HADOOP_DATA_DIR|g" $DLA_HADOOP_CONF_TEMPLATE_DIR/yarn-site.template.xml > $DLAHOME/etc/conf/hadoop/yarn-site.xml
sed -e "s|DLA_HADOOP_DATA_DIR|$DLA_HADOOP_DATA_DIR|g" $DLA_HADOOP_CONF_TEMPLATE_DIR/ssl-client.template.xml > $DLAHOME/etc/conf/hadoop/ssl-client.xml
sed -e "s|DLA_HADOOP_DATA_DIR|$DLA_HADOOP_DATA_DIR|g" $DLA_HADOOP_CONF_TEMPLATE_DIR/ssl-server.template.xml > $DLAHOME/etc/conf/hadoop/ssl-server.xml
