#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $YELLOW$BOLD"Stopping Apache Zookeeper..."$NOBOLD$NOCOLOR
echo

$ZOOKEEPER_HOME/bin/zkServer.sh stop $ZOOKEEPER_CONF_FILE
echo
