#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

echo -e $YELLOW$BOLD"Stopping Apache Zookeeper..."$NOBOLD$NOCOLOR
echo

$ZOOKEEPER_HOME/bin/zkServer.sh stop $ZOOKEEPER_CONF_FILE
echo
