#!/usr/bin/env bash

# Copyright (c) Datalayer, Inc https://datalayer.io
# Distributed under the terms of the MIT License.

DSP_SKIP_HEADER=true dla zookeeper-stop
DSP_SKIP_HEADER=true dla zookeeper-start
