apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: jupyters.gcp.datalayer.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: gcp.datalayer.io
  names:
    kind: Jupyter
    listKind: JupyterList
    singular: jupyter
    plural: jupyters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Jupyter is a composite resource that represents a K8S Cluster with an example ui installed
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterVersion:
                  type: string
                  description: GKE cluster version
                nodesCount:
                  type: integer
                  description: GKE cluster number of nodes
              required:
                - clusterVersion
                - nodesCount
