auth:
  clusterType: "gke"
  image: gcr.io/datalayer-dev-1/dsp-auth:0.0.3
#  imagePullPolicy: IfNotPresent
  imagePullPolicy: Always
  sidecar:
    image: gcr.io/datalayer-dev-1/k8s-sidecar:0.0.3
#  imagePullPolicy: IfNotPresent
  imagePullPolicy: Always
  port: 9700
  service:
    name: auth
    type: NodePort
#  resources:
#    limits:
#      memory: "8192Mi"
#      cpu: "3000m"
  env:
    DLAHOST: "datalayer.io"
    DSP_AUTH_JOIN_ERROR: "https://datalayer.io/join/error"
    DSP_AUTH_JOIN_SUCCESS: "https://datalayer.io/join/welcome"
    DSP_AUTH_PASSWORD_ERROR: "https://datalayer.io/new/password/error"
    DSP_AUTH_PASSWORD_SUCCESS: "https://datalayer.io/new/password/welcome"
    DSP_AUTH_ROOT_URL: "https://datalayer.io"
    DSP_AUTH_UI_REDIRECT: "https://datalayer.io"
    DSP_SOLR_ZK_HOST: "dsp-solr-zookeeper-0.dsp-solr-zookeeper-headless.dsp-solr"
    DSP_AUTH_AUTH_CALLBACK: "https://datalayer.io/oidc_callback"
    DSP_LDAP_HOST: "dsp-ldap-openldap"
    DSP_KEYCLOAK_SCHEME_HOST: "https://datalayer.io"
