{{ if eq .Values.jupyterpool.clusterType "minikube" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyterpool-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$3
spec:
  rules:
  - host: minikube.local
    http:
      paths:
      - path: /(api/jupyterpool)(/|$)(.*)
        backend:
          serviceName: {{ .Release.Name }}-jupyterpool-svc
          servicePort: {{ .Values.jupyterpool.port }}
{{- end }}
