apiVersion: v1
kind: ReplicationController
metadata:
  name: rcdla
spec:
  replicas: 2
  selector:
    app: dla
  template:
    metadata:
      name: somename
      labels:
        app: dla
    spec:
      containers:
      - name: dla
        image: datalayer/simple:0.0.3
        ports:
        - containerPort: 9876
