apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-landing-svc
  labels:
    app: {{ template "landing.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.landing.port }}
    name: landing-http
  selector:
    app: {{ template "landing.name" . }}
    release: {{ .Release.Name }}
