name: etcd
home: https://github.com/coreos/etcd
version: ${DLAVERSION}
description: Distributed reliable key-value store for the most critical data of a distributed system.
icon: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-horizontal-color.png

