apiVersion: v1
description: Kuber.
name: kuber
version: 0.0.3
appVersion: 0.0.3
home: https://datalayer.io
sources:
- https://github.com/datalayer/datalayer/tree/master/apps/kuber
icon: https://docs.datalayer.io/logo/datalayer-square.png
maintainers:
- name: eric
  email: eric@datalayer.io
