# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

FROM jupyterhub/k8s-hub:0.9-dcde99a

RUN pip3 install --no-cache-dir \
  jupyterhub-hmacauthenticator
